<?php 
use Core\Views as Views;
use Core\Caches as Caches;

class Index extends Views\ViewsClass {

    private $cache;

    public function __construct($metodos) {

        $this->cache = new Caches\Cache();

        $cache = $this->cache->read('cache_view_index');

        $this->load_controller("Index_controller");
        $post = $this->POST();

        if($post != null) {
            echo $this->controller->setIndex($post);
            exit;
        }

        $render = $this->load_html("Index");
        $render = $this->setDATA_HTML("{{TITLE}}", 'DM Framework - Sua plataforma com facilidade
        Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
        Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.
Com esse comando ele criará os arquivos para o seu livro. Seguindo o exemplo da wiki usei o “mybook” [você é livre para escolher um nome mais criativo para o arquivo].
Você pode começar a editar e adicionar conteúdos, imagens, fontes na pasta mybook_raw e já preencher os metadados em mybook_recipe.yaml usando qualquer editor de textos simples [como o Bloco de Notas no Windows, por exemplo]. Nesse arquivo você ainda pode determinar a ordem, os nomes dos capítulos etc.
Já os conteúdos você acrescenta nos arquivos TXT. Exemplos de uso [tabelas, itálicos etc.] podem ser encontrados nos arquivos do exemplo [em demo_raw]. A cada edição, basta rodar o comando outra vez, e o programa recriará o arquivo atualizado.

        ', $render); 
        $render = $this->setDATA_HTML("{{SITE_NAME}}", 'DM Framework', $render);
        $render = $this->setDATA_HTML("{{PATH_IMAGES}}", PATH_TEMPLATE . "/" . TEMPLATE . "/" . PATH_ASSETS, $render);

        if (!$cache) {
            $cache = $render;
            $this->cache->save('cache_view_index', $cache, '30 seconds');
        }

        print $cache;
    }
 
}